Fix compile error with latest realtime_tools
Recent commit in realtime_tools [1] causes the following compilation
failure:

    battery_state_broadcaster/src/BatteryStateBroadcaster.cpp:28:24:
    error: ‘sensor_msgs::msg::BatteryState_<std::allocator<void> >
    realtime_tools::RealtimePublisher<sensor_msgs::msg::BatteryState_<std::allocator<void>
    > >::msg_’ is private within this context

This commit fixes that.

[1]: https://github.com/ros-controls/realtime_tools/pull/423/commits/9e26e41bc49f9439cc9754bd5941c615a8599098